#include "ifthenlooplooptail.h"

static int v;

__attribute__((noinline)) static int foo(int n, int m)
{
  return v++;
}

int ifthenlooplooptail_enter(__attribute((secret)) int a, int b)
{
  int result = 3;

  if (a < b)
  {
    int i;

    for (i=0; i<3; i++)
    {
      int j;
      int r;

      /* Head */
      if (a == 12)
        foo(i, j);

      /* Nested loop */
      for (j=0; j<3; j++)
      {
        r = foo(i, j);
      }

      /* Tail */
      if (b == 12)
        foo(r, r*r);
    }
  }

  return result;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used)) static int _nds_foo(int n, int m) { return v; }
__attribute__((noinline, used)) static int _ndd_foo(int n, int m) { return v; }
#endif
