#include "ifthenlooploop.h"

static int v;

__attribute__((noinline)) static void foo(int n, int m)
{
  n < m ? v++ : v--;
}

int ifthenlooploop_enter(__attribute((secret)) int a, int b)
{
  int result = 3;

  if (a < b)
  {
    int i;

    for (i=0; i<3; i++)
    {
      int j;

      for (j=0; j<4; j++)
      {
        foo(i, j);
      }
    }
  }

  return result;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used)) static void _nds_foo(int i) { asm("nop"); }
__attribute__((noinline, used)) static void _ndd_foo(int i) { asm("nop"); }
#endif
