#include "ifthenlooploop.h"

static int v;

// Setting the section prevents this function from being included in the
// hardened binary (when the compiled with -Wl,gc-sections). This should be
// handled by SLLVM but this feature is not supported yet.
__attribute__((section(".sllvm.text.ifthenlooploop.vulnerable"), noinline))
static void foo(int n, int m)
{
  n < m ? v++ : v--;
}

int ifthenlooploop_enter(__attribute__((secret)) int a, int b)
{
  int result = 3;

  if (a < b)
  {
    int i;

    for (i=0; i<3; i++)
    {
      int j;

      for (j=0; j<4; j++)
      {
        foo(i, j);
      }
    }
  }

  return result;
}

// The following functions should be generated by SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((section(".sllvm.text.ifthenlooploop.nemdef"), noinline, used))
static void _nds_foo(int i) 
{ 
  asm("\tmov #1, r14\n"
      "\tcmp r13, r12\n"
      "\tjl .LOC1\n"
      "\tmov #-1, r14\n"
      "\tjmp .LOC2\n"
      ".LOC1:\n"
      "\tnop\n"
      "\tjmp .LOC2\n"
      ".LOC2:\n"
      "\tadd r14, &v\n");
}

__attribute__((section(".sllvm.text.ifthenlooploop.nemdef"), noinline, used))
static void _ndd_foo(int i) 
{ 
  asm("\tmov r10, r10\n"
      "\tmov r10, r10\n"
      "\tmov #42, r3\n"
      "\tmov r10, r10\n"
      "\tmov #42, r3\n"
      "\tbis #0xFFFF, &dma_dummy_data\n");
}
#endif
