EXE = ifthenlooploop.nemdef

ifthenlooploop.ll: CFLAGS += -Os
#ifthenlooploop.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#ifthenlooploop.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): ifthenlooploop.nemdef.o
$(EXE): main.o
