EXE = triangle.nemdef

triangle.ll: CFLAGS += -Os
#triangle.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#triangle.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: triangle.nemdef.o
$(EXE).nomac: main.o
