EXE = triangle.nemdef

triangle.ll: CFLAGS += -Os
#triangle.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): triangle.nemdef.o
$(EXE): main.o
