EXE = loop.nemdef

loop.ll: CFLAGS += -Os
#loop.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#loop.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: loop.nemdef.o
$(EXE).nomac: main.o
