#include "modexp2.h"

#define MOD 7

int modexp2_enter(int y, __attribute__((secret)) int k)
{
  int r = 1;

  for (int i = 0; i < (sizeof(int) * 8); i++)
  {
    if ((k % 2) == 1)
    {
      r = (r * y) % MOD;
      y = (y * y) % MOD;
      k >>= 1;
    }
  }

  return r % MOD;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used))
static void _nds___mspabi_mpyi(int a, int b) { asm("nop"); }
__attribute__((noinline, used))
static void _ndd___mspabi_mpyi(int a, int b) { asm("nop"); }
__attribute__((noinline, used))
static void _nds___mspabi_remu(int a, int b) { asm("nop"); }
__attribute__((noinline, used))
static void _ndd___mspabi_remu(int a, int b) { asm("nop"); }
__attribute__((noinline, used))
static void _nds___mspabi_remi(int a, int b) { asm("nop"); }
__attribute__((noinline, used))
static void _ndd___mspabi_remi(int a, int b) { asm("nop"); }
#endif
