EXE = fork.nemdef

fork.ll: CFLAGS += -Os
#fork.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#fork.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): fork.nemdef.o
$(EXE): main.o
