#include "ifthenloopif.h"

static int v = 0;

__attribute__((noinline)) static int foo(int i)
{
  v += i;

  return v;
}

int ifthenloopif_enter(__attribute__((secret)) int a, int b)
{
  int result = 3;

  if (a < b)
  {
    int i;

    for (i=0; i<3; i++)
    {
      if ((b + foo(1)) < a)
      {
        (void) foo(b);
      }
    }
  }

  return result;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used)) static int _nds_foo(int i) { return v++; }
__attribute__((noinline, used)) static int _ndd_foo(int i) { return v++; }
#endif
