EXE = ifthenloopif.nemdef

ifthenloopif.ll: CFLAGS += -Os
#ifthenloopif.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): ifthenloopif.nemdef.o
$(EXE): main.o
