#include "ifthenloop.h"

static int v;

__attribute__((noinline)) static void bar(int i)
{
	v++;
}

int ifthenloop_enter(__attribute((secret)) int a, int b)
{
  int result = 3;

  if (a < b)
  {
    int i;

    for (i=0; i<1023; i++)
    {
      bar(i);
    }
  }

  return result;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used)) static void _nds_bar(int i)
{
	v++;
}

__attribute__((noinline, used)) static void _ndd_bar(int i)
{
	v++;
}
#endif

