#include "ifthenloop.h"

static int v;

__attribute__((noinline)) static void foo(int i)
{
  v++;
}

int ifthenloop_enter(__attribute__((secret)) int a, int b)
{
  int result = 3;

  if (a < b)
  {
    int i;

    for (i=0; i<3; i++)
    {
      foo(i);
    }
  }

  return result;
}

// The following functions should be generated by SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used)) static void _nds_foo(int i) 
{ 
  asm("\tinc &v\n"); 
  asm("\tret\n"); 
}

__attribute__((noinline, used)) static void _ndd_foo(int i) 
{ 
  asm("\tadd #0, &v\n"); 
  asm("\tret\n"); 
}
#endif

