#include "ifthenloop.h"

static int v;

__attribute__((noinline)) static void bar(int i)
{
	v++;
}

// This should be generated by the compiler
__attribute__((noinline)) static void _nds_bar(int i)
{
	v++;
}

// This should be generated by the compiler
__attribute__((noinline)) static void _ndd_bar(int i)
{
	v++;
}

int ifthenloop_enter(__attribute((secret)) int a, int b)
{
  int result = 3;

  _nds_bar(10); // Prevents the compiler from ignoring _nds_bar
  _ndd_bar(10); // Prevents the compiler from ignoring _ndd_bar

  if (a < b)
  {
    int i;

    for (i=0; i<1023; i++)
    {
      bar(i);
    }
  }

  return result;
}
