EXE = ifthenloop.nemdef

ifthenloop.ll: CFLAGS += -Os
#ifthenloop.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#ifthenloop.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): ifthenloop.nemdef.o
$(EXE): main.o
