EXE = mathf.ifc.nemdef

#mathf.ll: CFLAGS += -Os

#mathf.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#mathf.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true
#mathf.nemdef.s: LLCFLAGSNEMDEF += -print-machineinstrs
#mathf.nemdef.s: LLCFLAGSNEMDEF += -filter-print-funcs=mathf_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: mathf.nemdef.o
$(EXE).nomac: main.o
