EXE = mathf.ifc.vulnerable

#mathf.ll: CFLAGS += -Os
	
#mathf.s: LLCFLAGS += -print-machineinstrs
#mathf.s: LLCFLAGS += -filter-print-funcs=mathf_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: mathf.o
$(EXE).nomac: main.o
