EXE = threeway.nemdef

threeway.ll: CFLAGS += -Os
#threeway.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#threeway.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: threeway.nemdef.o
$(EXE).nomac: main.o
