EXE = matrixmul.nemdef

#matrixmul.ll: CFLAGS += -Os

#matrixmul.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#matrixmul.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true
#matrixmul.nemdef.s: LLCFLAGSNEMDEF += -print-machineinstrs
#matrixmul.nemdef.s: LLCFLAGSNEMDEF += -filter-print-funcs=matrixmul_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: matrixmul.nemdef.o
$(EXE).nomac: main.o
