EXE = xxx.nemdef

xxx.ll: CFLAGS += -Os
#xxx.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#xxx.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): xxx.nemdef.o
$(EXE): main.o
