EXE = kruskal.ifc.nemdef

#kruskal.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#kruskal.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: kruskal.nemdef.o
$(EXE).nomac: main.o
