EXE = switch16.ifc.vulnerable

#switch16.s: LLCFLAGS += -print-machineinstrs
#switch16.s: LLCFLAGS += -filter-print-funcs=switch16_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: switch16.o
$(EXE).nomac: main.o
