EXE = switch16.ifc.nemdef

#switch16.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#switch16.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true
#switch16.nemdef.s: LLCFLAGSNEMDEF += -print-machineinstrs
#switch16.nemdef.s: LLCFLAGSNEMDEF += -filter-print-funcs=switch16_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: switch16.nemdef.o
$(EXE).nomac: main.o
