EXE = sharevalue.ifc.nemdef

#sharevalue.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#sharevalue.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: sharevalue.nemdef.o
$(EXE).nomac: main.o
