EXE = diamond.nemdef

diamond.ll: CFLAGS += -Os
#diamond.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: diamond.nemdef.o
$(EXE).nomac: main.o
