#include "call.h"

static volatile int v = 0;

__attribute__((noinline)) static int foo(int x)
{
  v = x;

  return v++;
}

int call_enter(__attribute__((secret)) int a, int b)
{
  if (a == 2)
  {
    return foo(b);
  }

  return 0;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
asm(".equiv _nds_foo, foo");

__attribute__((noinline, used)) static void _ndd_foo(int v) { 
  asm("MOV R10, &dma_dummy_data");
  asm("BIC &dma_dummy_text, R3");
  asm("MOV R4, R4");
  asm("MOV R4, R4");
  asm("MOV R10, &dma_dummy_data");
}
#endif

