#include "call.h"

static int v = 0;

__attribute__((noinline)) static int foo(int v)
{
  return v++;
}

int call_enter(__attribute__((secret)) int a, int b)
{
  if (a == 2)
  {
    return foo(b);
  }

  return 0;
}

// The following functions should be generated by the SLLVM but this feature
// is not supported yet.
#if 1
__attribute__((noinline, used)) static int _nds_foo(int v) { return 1; }
__attribute__((noinline, used)) static int _ndd_foo(int v) { return 1; }
#endif

