EXE = call.nemdef

call.ll: CFLAGS += -Os
#call.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#call.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: call.nemdef.o
$(EXE).nomac: main.o
