EXE = math32.nemdef

#math32.ll: CFLAGS += -Os

#math32.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#math32.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true
#math32.nemdef.s: LLCFLAGSNEMDEF += -print-machineinstrs
#math32.nemdef.s: LLCFLAGSNEMDEF += -filter-print-funcs=math32_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: math32.nemdef.o
$(EXE).nomac: main.o
