EXE = bsl.nemdef

bsl.ll: CFLAGS += -Os
#bsl.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: bsl.nemdef.o
$(EXE).nomac: main.o
