EXE = matrixmul.ifc.vulnerable

#matrixmul.s: LLCFLAGS += -print-machineinstrs
#matrixmul.s: LLCFLAGS += -filter-print-funcs=matrixmul_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: matrixmul.o
$(EXE).nomac: main.o
