EXE = switch8.ifc.nemdef

#switch8.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#switch8.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true
#switch8.nemdef.s: LLCFLAGSNEMDEF += -print-machineinstrs
#switch8.nemdef.s: LLCFLAGSNEMDEF += -filter-print-funcs=switch8_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: switch8.nemdef.o
$(EXE).nomac: main.o
