EXE = switch8.vulnerable

#switch8.ll: CFLAGS += -Os
	
#switch8.s: LLCFLAGS += -print-machineinstrs
#switch8.s: LLCFLAGS += -filter-print-funcs=switch8_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: switch8.o
$(EXE).nomac: main.o
