EXE = indirect.nemdef

indirect.ll: CFLAGS += -Os

#indirect.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#indirect.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: indirect.nemdef.o
$(EXE).nomac: main.o
