EXE = mulhi3.nemdef

mulhi3.ll: CFLAGS += -Os
#mulhi3.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#mulhi3.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: mulhi3.nemdef.o
$(EXE).nomac: main.o
