EXE = keypad.ifc.vulnerable

#keypad.ll: CFLAGS += -Os
	
#keypad.s: LLCFLAGS += -print-machineinstrs
#keypad.s: LLCFLAGS += -filter-print-funcs=keypad_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: keypad.o
$(EXE).nomac: main.o
