EXE = multifork.nemdef

multifork.ll: CFLAGS += -Os
#multifork.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#multifork.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): multifork.nemdef.o
$(EXE): main.o
