EXE = modexp.nemdef

modexp.ll: CFLAGS += -Os
#modexp.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#modexp.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE): modexp.nemdef.o
$(EXE): main.o
