EXE = ifcompound.nemdef

ifcompound.ll: CFLAGS += -Os
#ifcompound.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#ifcompound.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: ifcompound.nemdef.o
$(EXE).nomac: main.o
