EXE = mulmod8.ifc.nemdef

#mulmod8.nemdef.s: LLCFLAGSNEMDEF += -debug-only=msp430-nemesis-defender
#mulmod8.nemdef.s: LLCFLAGSNEMDEF += -msp430-nemesis-defender-emit-cfg=true
#mulmod8.nemdef.s: LLCFLAGSNEMDEF += -print-machineinstrs
#mulmod8.nemdef.s: LLCFLAGSNEMDEF += -filter-print-funcs=mulmod8_

include ../Makefile.include

LDFLAGS += -lsancus-step

$(EXE).nomac: mulmod8.nemdef.o
$(EXE).nomac: main.o
